[Back-End] [ENHANCEMENT] - Created questionnaire app and created its models
TheInspiredConjurer/Online-Questionnaire-System pull request #7
Opened 2022-10-03 10:32 UTC by chukaibejih

- I created a new app called "questionnaire"
- Created three models ( Question, Answer and Category)
- Created a superuser
- Ran migrations

2022-10-03 15:20 UTC, TheInspiredConjurer commented
Hey @chukaibejih Thanks for submitting a PR! However, there are some issues with it.

Please write your PR message according to the guidelines mentioned in `CONTRIBUTING.md`

Also, your models are not quite right. Please have a look at #3 and design your models according to them.

Also, make a separate app for every requirement... e.g. a separate app for questions, a separate app for choices, etc,

Also also, This project uses Django REST framework in the backend, hence please use the same. Do not use plain Django.

2022-10-03 15:55 UTC, Vir2S approved these changes

2022-10-05 11:18 UTC, TheInspiredConjurer requested changes
- design models according to https://github.com/TheInspiredConjurer/Online-Questionnaire-System/issues/3 .

- Make separate app for every requirement... e.g. a separate app for questions, a separate app for choices, etc,

- Use Django REST framework in the backend, not plain Django.

2022-10-05 16:07 UTC, chukaibejih commented
Hello thank you for the review. I'll be able to look at it over the weekend if that's okay.  I've been so busy with work.

2022-10-06 15:25 UTC, closed without merging